### ISSUE TITLE
NetAppCollector expects arguments to collect() method

### ISSUE THREAD

**Issue by powo** [python-diamond/Diamond#146]
The `collect` in the `netapp` collector classes expects additional arguments, but `.collect()` isn't called with any arguments.

```
# diamond -f -l -c /etc/diamond/diamond.conf -r /usr/share/diamond/collectors/netapp/netappDisk.py
...
...
1427756106.58   [NetAppCollector:21294:DEBUG]   Starting
1427756106.59   [NetAppCollector:21294:DEBUG]   Interval: 300.0 seconds
1427756106.59   [NetAppCollector:21294:DEBUG]   Max collection time: 270 seconds
1427756106.59   [NetAppCollector:21294:ERROR]   Collector failed!
1427756106.59   [NetAppCollector:21294:ERROR]   /usr/lib/python2.6/site-packages/diamond/utils/scheduler.py:87
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/diamond/utils/scheduler.py", line 63, in collector_process
    collector._run()
  File "/usr/lib/python2.6/site-packages/diamond/collector.py", line 472, in _run
    self.collect()
TypeError: collect() takes exactly 5 arguments (1 given)
...
...
```

This seems to be the only plugin affected, but I don't know how this ever worked ... has the API been changed in the past ?

```
# fgrep -r 'def collect(' /usr/share/diamond/collectors/ |fgrep -v 'def collect(self):'

/usr/share/diamond/collectors/netapp/netapp_inode.py:    def collect(self, device, ip, user, password):
/usr/share/diamond/collectors/netapp/netapp.py:    def collect(self, device, ip, user, password):
/usr/share/diamond/collectors/netapp/netappDisk.py:    def collect(self, device, ip, user, password):
```

**Comment by Gug42** [comment]
Hello,

I have the same issue here ...  
I have try another "netapp collector" , wihtout success ... can you test it plz ?
https://github.com/SpringerPE/diamond-ontapclustercollector

I'm using diamond version 4.0.181

Thank you in advance.

**Comment by DStape** [comment]
Hello @powo, @Gug42,

I can see that this still remains a problem (and only for this specific collector):
```~/git/dstape/Diamond/src/collectors (master)$ git grep def\ collect\(self\\,
netapp/netapp.py:    def collect(self, device, ip, user, password):
netapp/netappDisk.py:    def collect(self, device, ip, user, password):
netapp/netapp_inode.py:    def collect(self, device, ip, user, password):```

I don't know much about the history of diamond or how this collector remains in the current state that it's in (and I unfortunately I don't have the cycles to study the git log), but I think it's reasonable to assert that this collector wasn't updated whenever the ```collect``` api changed.

If you'd still like to see this work, ```device, ip, user, password``` can be removed from the method signature and where they are referenced in the method's implementation, replace the ref with self.config.get(```device, etc```) instead, as these values are expected to exist as part of the config.

Even with the above suggestion though, the code needs a lot of TLC, for instance, on every invocation of ```collect```, there's a ```try - except``` block where the code attempts to import some netapp library - this is something that should be done when the collector is initally loaded, not on every collection which could be as much as every second.

Anyhow, @josegonzalez , can this issue be closed please? (If there is still interest in this plugin, please feel free to contribute by opening a new issue/pr.)
