### ISSUE TITLE
InfluxDBClientError: 400: {"error":"missing measurement"}

### ISSUE THREAD

**Issue by gavinzhou** [python-diamond/Diamond#217]
I get this error message

[2015-07-08 16:02:25,114] [MainThread] "POST /write?p=root&u=root HTTP/1.1" 400 56
[2015-07-08 16:02:25,115] [MainThread] InfluxdbHandler: Error sending metrics, waiting for 32s.
[2015-07-08 16:02:25,115] [MainThread] Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/diamond/handler/Handler.py", line 72, in _process
    self.process(metric)
  File "/usr/lib/python2.7/site-packages/diamond/handler/influxdbHandler.py", line 151, in process
    self._send()
  File "/usr/lib/python2.7/site-packages/diamond/handler/influxdbHandler.py", line 182, in _send
    time_precision=self.time_precision)
  File "/usr/local/lib/python2.7/site-packages/influxdb/client.py", line 368, in write_points
    tags=tags)
  File "/usr/local/lib/python2.7/site-packages/influxdb/client.py", line 410, in _write_points
    expected_response_code=204
  File "/usr/local/lib/python2.7/site-packages/influxdb/client.py", line 262, in write
    expected_response_code=expected_response_code
  File "/usr/local/lib/python2.7/site-packages/influxdb/client.py", line 242, in request
    raise InfluxDBClientError(response.content, response.status_code)
InfluxDBClientError: 400: {"error":"missing measurement"}

**Comment by gavinzhou** [comment]
Python 2.7.9 (default, Apr  1 2015, 18:18:03)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import influxdb
>>> influxdb.__version__
'2.6.0'

**Comment by gavinzhou** [comment]
change "name" to "measurement", this working

#148 
thank you

```python
                    # build metrics data
                    metrics = []
                    if self.influxdb_version == "0.8":
                        for path in self.batch:
                            metrics.append({
                                "points": self.batch[path],
                                "name": path,
                                "columns": ["time", "value"]})
                    elif self.influxdb_version == "0.9":
                        for path in self.batch:
                            metrics.append({
                                "measurement": path,
                                "precision": self.time_precision,
                                "time": self.batch[path][0][0],
                                "fields": {"value": self.batch[path][0][1]}})
                    # Send data to influxdb
                    self.log.debug("InfluxdbHandler: writing %s series of data", metrics)
                    self.log.debug("InfluxdbHandler: writing %d series of data",
                                   len(metrics))
                    self.influx.write_points(metrics,
                                             time_precision=self.time_precision)
```
