### ISSUE TITLE
SNMP collector not working 

### ISSUE THREAD

**Issue by harishva** [python-diamond/Diamond#219]
[root@graphite collectors]# cat SNMPInterfaceCollector.conf
enabled = True
path_suffix = ""
retries = 3
measure_collector_time = False
byte_unit = byte
timeout = 5

path = interface
interval = 60

[devices]
[fw01]]
host = 192.168.1.1
port = 161
community = public
# here  goes logs 

Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/diamond/utils/scheduler.py", line 70, in collector_process
    collector._run()
  File "/usr/lib/python2.6/site-packages/diamond/collector.py", line 472, in _run
    self.collect()
  File "/usr/lib/python2.6/site-packages/diamond/collector.py", line 366, in collect
    raise NotImplementedError()
NotImplementedError
[2015-07-08 13:56:56,318] [MainThread] Collector failed!
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/diamond/utils/scheduler.py", line 70, in collector_process
    collector._run()
  File "/usr/lib/python2.6/site-packages/diamond/collector.py", line 472, in _run
    self.collect()
  File "/usr/lib/python2.6/site-packages/diamond/collector.py", line 366, in collect
    raise NotImplementedError()
NotImplementedError
[2015-07-08 13:56:58,332] [MainThread] Collector failed!
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/diamond/utils/scheduler.py", line 70, in collector_process
    collector._run()
  File "/usr/lib/python2.6/site-packages/diamond/collector.py", line 472, in _run
    self.collect()
  File "/usr/lib/python2.6/site-packages/diamond/collector.py", line 366, in collect
    raise NotImplementedError()
NotImplementedError

**Comment by superjeb** [comment]
I'm having the same issue. 

Is there a fix?

**Comment by superjeb** [comment]
NotImplementedError
[2015-07-30 22:17:29,256] [MainThread] Collector failed!
Traceback (most recent call last):
  File "/opt/diamond/lib/python2.7/site-packages/diamond/utils/scheduler.py", line 70, in collector_process
    collector._run()
  File "/opt/diamond/lib/python2.7/site-packages/diamond/collector.py", line 472, in _run
    self.collect()
  File "/opt/diamond/lib/python2.7/site-packages/diamond/collector.py", line 366, in collect
    raise NotImplementedError()
NotImplementedError
[2015-07-30 22:17:30,756] [MainThread] Collector failed!
Traceback (most recent call last):
  File "/opt/diamond/lib/python2.7/site-packages/diamond/utils/scheduler.py", line 70, in collector_process
    collector._run()
  File "/opt/diamond/lib/python2.7/site-packages/diamond/collector.py", line 472, in _run
    self.collect()
  File "/opt/diamond/lib/python2.7/site-packages/diamond/collector.py", line 366, in collect
    raise NotImplementedError()

**Comment by jaykumar2001** [comment]
+1

**Comment by jrpaz** [comment]
+2 also

**Comment by frlinux** [comment]
+3

**Comment by bmfurtado** [comment]
I've created this pull request with an initial version of what could fix this... needs feedback and testing! https://github.com/python-diamond/Diamond/pull/310

**Comment by bakerkj** [comment]
I was having this same issue.  Pulling the change above seems to address it.

Thanks

**Comment by claytondukes** [comment]
Can someone let me know how to fix this if it's on a Debian server? (installed using pypi-install diamond)

**Comment by eugenepaniot** [comment]
It works! Thanks.

**Comment by bakerkj** [comment]
Is there anything holding up pulling this to master?

**Comment by krbaker** [comment]
works for me too

**Comment by phrend** [comment]
I'm trying to get SNMPInterfaceCollector working and am getting the same errors. I tried using https://raw.githubusercontent.com/bmfurtado/Diamond/%23219/src/collectors/snmp/snmp.py but still get the error. I'm totally open to the possibility that I'm doing something else wrong!

(using diamond==4.0.195 and pysnmp==4.3.2)

**Comment by kstaniek** [comment]
+1

**Comment by josegonzalez** [comment]
Closed by #310. Thanks for the pull request!
