### ISSUE TITLE
Kafka Collector error with urllib2

### ISSUE THREAD

**Issue by maauso** [python-diamond/Diamond#225]
Hi, 
I try connect kafka collection with kafka 0.8.2. 

[2015-07-17 11:44:56,298] [MainThread] ''
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/diamond/collector.py", line 472, in _run
    self.collect()
  File "/usr/share/diamond/collectors/kafkastat/kafkastat.py", line 163, in collect
    match = self.get_mbeans(pattern)
  File "/usr/share/diamond/collectors/kafkastat/kafkastat.py", line 84, in get_mbeans
    mbeans = self._get('/serverbydomain', query_args)
  File "/usr/share/diamond/collectors/kafkastat/kafkastat.py", line 70, in _get
    response = urllib2.urlopen(url)
  File "/usr/lib64/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1216, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib64/python2.7/urllib2.py", line 1189, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib64/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/usr/lib64/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python2.7/httplib.py", line 373, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''

Any idea?

**Comment by iurii-polishchuk** [comment]
I've got the same issue. It seems some kafka http reporter is required to expose jmx via http.

**Comment by iurii-polishchuk** [comment]
Also actual documentation for KafkaCollector is highly appreciated.

**Comment by iurii-polishchuk** [comment]
@maauso, download [mx4j-tools](http://mvnrepository.com/artifact/mx4j/mx4j-tools/3.0.1) into your kafka libs (in my case it was /usr/lib/kafka/libs) and restart kafka broker. After that mx4j adaptor will listen on port 8082 and KafkaCollector is able to read kafka metrics.

**Comment by maauso** [comment]
@iruii-Polishchukka thanks I'll try it, finally I used jmxtrans, but I think that in this case diamond is best solution

**Comment by iurii-polishchuk** [comment]
@maauso another option is to use [JolokiaCollector](https://diamond.readthedocs.org/en/latest/collectors/JolokiaCollector/).

**Comment by ddreggors** [comment]
I have just upgraded to kafka 0.8.2.2 (from 0.8.2.2) and I have mx4j-tools installed. I see no errors in diamond logs but all stats have stopped in graphite. I can browse to kafka servers on port 8082 and see all metrics.

Any clues?

**Comment by shortdudey123** [comment]
@ddreggors can you add any diamond debug logs here?

**Comment by ddreggors** [comment]
I have a snippet of 2 logs since I restarted with DEBUG set:

This node shows an error involving a topic that is deleted. I cannot even see topic in zookeeper.
`[2016-08-03 02:06:19,235] [Thread-12] Collecting data from: MemoryCollector
[2016-08-03 02:06:19,288] [Thread-1] Collecting data from: CPUCollector
[2016-08-03 02:06:19,306] [Thread-1] GraphitePickleHandler: Sending batch size: 256
[2016-08-03 02:06:19,317] [Thread-1] GraphitePickleHandler: Sending batch size: 256
[2016-08-03 02:06:19,318] [Thread-1] Collecting data from: ZookeeperCollector
[2016-08-03 02:06:19,318] [Thread-13] Collecting data from: SmartCollector
[2016-08-03 02:06:19,321] [Thread-1] pid None
[2016-08-03 02:06:19,321] [Thread-1] Cannot parse command line options for zookeeper
[2016-08-03 02:06:19,323] [Thread-14] Collecting data from: DiskSpaceCollector
[2016-08-03 02:06:19,323] [Thread-1] Collecting data from: UDPCollector
[2016-08-03 02:06:19,323] [Thread-14] Ignoring / since it is of type rootfs which  is not in the list of filesystems.
[2016-08-03 02:06:19,323] [Thread-14] Ignoring /proc since it is of type proc which  is not in the list of filesystems.
[2016-08-03 02:06:19,323] [Thread-14] Ignoring /sys since it is of type sysfs which  is not in the list of filesystems.
[2016-08-03 02:06:19,324] [Thread-14] Ignoring /dev since it is of type devtmpfs which  is not in the list of filesystems.
[2016-08-03 02:06:19,324] [Thread-14] Ignoring /dev/pts since it is of type devpts which  is not in the list of filesystems.
[2016-08-03 02:06:19,324] [Thread-14] Ignoring /dev/shm since it is of type tmpfs which  is not in the list of filesystems.
[2016-08-03 02:06:19,324] [Thread-14] Ignoring /proc/bus/usb since it is of type usbfs which  is not in the list of filesystems.
[2016-08-03 02:06:19,325] [Thread-14] Ignoring /proc/sys/fs/binfmt_misc since it is of type binfmt_misc which  is not in the list of filesystems.
[2016-08-03 02:06:19,325] [Thread-1] Collecting data from: TCPCollector
[2016-08-03 02:06:19,329] [Thread-15] Collecting data from: KafkaCollector
[2016-08-03 02:06:19,330] [Thread-1] Collecting data from: MonitCollector
[2016-08-03 02:06:19,330] [Thread-16] Collecting data from: LoadAverageCollector
[2016-08-03 02:06:19,335] [Thread-13] ATTRIBUTE_NAME not found in second column of smartctl output between lines 4 and 9.
[2016-08-03 02:06:19,335] [Thread-1] Collecting data from: VMStatCollector
[2016-08-03 02:06:19,338] [Thread-1] Collecting data from: DiskUsageCollector
[2016-08-03 02:06:19,348] [Thread-1] Collecting data from: NetworkCollector
[2016-08-03 02:06:19,348] [Thread-13] ATTRIBUTE_NAME not found in second column of smartctl output between lines 4 and 9.
[2016-08-03 02:06:19,351] [Thread-1] GraphitePickleHandler: Sending batch size: 256
[2016-08-03 02:06:20,312] [Thread-15] http://kafka03:8082/mbean?operations=False&notifications=False&constructors=False&objectname=kafka.log%3Atype%3DLog%2Cname%3DLogStartOffset%2Ctopic%3Ddd_test%2Cpartition%3D10&template=identity: HTTP Error 500: Internal Server Error
[2016-08-03 02:06:20,313] [Thread-15] Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/diamond/collector.py", line 429, in _run
    self.collect()
  File "/usr/share/diamond/collectors/kafka/kafka.py", line 167, in collect
    metrics.update(stats)
TypeError: 'NoneType' object is not iterable
`

and here is another node that shows no error (same cluster)
`[2016-08-03 02:05:06,206] [Thread-1] Collecting data from: TCPCollector
[2016-08-03 02:05:06,211] [Thread-5] Collecting data from: KafkaCollector
[2016-08-03 02:05:06,213] [Thread-1] Collecting data from: MonitCollector
[2016-08-03 02:05:06,214] [Thread-3] ATTRIBUTE_NAME not found in second column of smartctl output between lines 4 and 9.
[2016-08-03 02:05:06,214] [Thread-6] Collecting data from: LoadAverageCollector
[2016-08-03 02:05:06,220] [Thread-1] Collecting data from: VMStatCollector
[2016-08-03 02:05:06,221] [Thread-1] Collecting data from: DiskUsageCollector
[2016-08-03 02:05:06,225] [Thread-1] Collecting data from: NetworkCollector
[2016-08-03 02:05:06,225] [Thread-3] ATTRIBUTE_NAME not found in second column of smartctl output between lines 4 and 9.
[2016-08-03 02:05:06,232] [Thread-1] GraphitePickleHandler: Sending batch size: 256
[2016-08-03 02:05:12,631] [Thread-5] GraphitePickleHandler: Sending batch size: 256
[2016-08-03 02:06:06,173] [Thread-7] Collecting data from: MemoryCollector
[2016-08-03 02:06:06,199] [Thread-1] Collecting data from: CPUCollector
[2016-08-03 02:06:06,223] [Thread-1] GraphitePickleHandler: Sending batch size: 256
[2016-08-03 02:06:06,230] [Thread-1] Collecting data from: ZookeeperCollector
[2016-08-03 02:06:06,230] [Thread-8] Collecting data from: SmartCollector
[2016-08-03 02:06:06,233] [Thread-1] pid None
[2016-08-03 02:06:06,233] [Thread-1] Cannot parse command line options for zookeeper
[2016-08-03 02:06:06,234] [Thread-9] Collecting data from: DiskSpaceCollector
[2016-08-03 02:06:06,234] [Thread-1] Collecting data from: UDPCollector
[2016-08-03 02:06:06,235] [Thread-9] Ignoring / since it is of type rootfs which  is not in the list of filesystems.
[2016-08-03 02:06:06,235] [Thread-9] Ignoring /proc since it is of type proc which  is not in the list of filesystems.
[2016-08-03 02:06:06,235] [Thread-9] Ignoring /sys since it is of type sysfs which  is not in the list of filesystems.
[2016-08-03 02:06:06,235] [Thread-9] Ignoring /dev since it is of type devtmpfs which  is not in the list of filesystems.
[2016-08-03 02:06:06,235] [Thread-9] Ignoring /dev/pts since it is of type devpts which  is not in the list of filesystems.
[2016-08-03 02:06:06,235] [Thread-9] Ignoring /dev/shm since it is of type tmpfs which  is not in the list of filesystems.
[2016-08-03 02:06:06,235] [Thread-9] Ignoring /proc/bus/usb since it is of type usbfs which  is not in the list of filesystems.
[2016-08-03 02:06:06,236] [Thread-9] Ignoring /proc/sys/fs/binfmt_misc since it is of type binfmt_misc which  is not in the list of filesystems.
[2016-08-03 02:06:06,237] [Thread-1] Collecting data from: TCPCollector
[2016-08-03 02:06:06,241] [Thread-10] Collecting data from: KafkaCollector
[2016-08-03 02:06:06,242] [Thread-11] Collecting data from: LoadAverageCollector
[2016-08-03 02:06:06,242] [Thread-1] Collecting data from: MonitCollector
[2016-08-03 02:06:06,243] [Thread-8] ATTRIBUTE_NAME not found in second column of smartctl output between lines 4 and 9.
[2016-08-03 02:06:06,249] [Thread-1] Collecting data from: VMStatCollector
[2016-08-03 02:06:06,258] [Thread-1] Collecting data from: DiskUsageCollector
[2016-08-03 02:06:06,259] [Thread-8] ATTRIBUTE_NAME not found in second column of smartctl output between lines 4 and 9.
[2016-08-03 02:06:06,262] [Thread-1] GraphitePickleHandler: Sending batch size: 256
[2016-08-03 02:06:06,269] [Thread-1] Collecting data from: NetworkCollector
[2016-08-03 02:06:12,739] [Thread-10] GraphitePickleHandler: Sending batch size: 256
[2016-08-03 02:07:06,179] [Thread-12] Collecting data from: MemoryCollector
[2016-08-03 02:07:06,230] [Thread-1] Collecting data from: CPUCollector
[2016-08-03 02:07:06,247] [Thread-1] GraphitePickleHandler: Sending batch size: 256
[2016-08-03 02:07:06,259] [Thread-1] GraphitePickleHandler: Sending batch size: 256
[2016-08-03 02:07:06,262] [Thread-13] Collecting data from: SmartCollector
[2016-08-03 02:07:06,262] [Thread-1] Collecting data from: ZookeeperCollector
[2016-08-03 02:07:06,271] [Thread-1] pid None
[2016-08-03 02:07:06,271] [Thread-1] Cannot parse command line options for zookeeper
[2016-08-03 02:07:06,273] [Thread-14] Collecting data from: DiskSpaceCollector
[2016-08-03 02:07:06,273] [Thread-1] Collecting data from: UDPCollector
[2016-08-03 02:07:06,273] [Thread-14] Ignoring / since it is of type rootfs which  is not in the list of filesystems.
[2016-08-03 02:07:06,273] [Thread-14] Ignoring /proc since it is of type proc which  is not in the list of filesystems.
[2016-08-03 02:07:06,273] [Thread-14] Ignoring /sys since it is of type sysfs which  is not in the list of filesystems.
[2016-08-03 02:07:06,273] [Thread-14] Ignoring /dev since it is of type devtmpfs which  is not in the list of filesystems.
[2016-08-03 02:07:06,273] [Thread-14] Ignoring /dev/pts since it is of type devpts which  is not in the list of filesystems.
[2016-08-03 02:07:06,273] [Thread-14] Ignoring /dev/shm since it is of type tmpfs which  is not in the list of filesystems.
[2016-08-03 02:07:06,274] [Thread-14] Ignoring /proc/bus/usb since it is of type usbfs which  is not in the list of filesystems.
[2016-08-03 02:07:06,274] [Thread-14] Ignoring /proc/sys/fs/binfmt_misc since it is of type binfmt_misc which  is not in the list of filesystems.
`

**Comment by ddreggors** [comment]
Disregard errors in node3 log, I fixed that with a restart of kafka. 
I am still unable to see kafka stats in graphite though. All other diamond stats are showing up in graphite for these nodes.

**Comment by ddreggors** [comment]
I was able to fix my issue. The parsing of the mx4j was broken in the version if diamond I have.

I can make it parse now by changing to this:

`--- /usr/share/diamond/collectors/kafka/kafka.py	2016-08-03 06:04:12.040443070 +0000
+++ /usr/share/diamond/collectors/lskafka/lskafka.py	2016-08-03 14:56:22.222793771 +0000
@@ -112,23 +112,21 @@
             return
 
         if key_prefix is None:
-            # Could be 1 or 2 = in the string
+            # Could be 1 or more = in the string
             # java.lang:type=Threading
-            # "kafka.controller":type="ControllerStats",name="LeaderElectionRateAndTimeMs"
-            split_num = objectname.count('=')
-            for i in range(split_num):
-              if i == 0:
-                key_prefix = objectname.split('=')[1]
-                if '"' in key_prefix:
-                  key_prefix = key_prefix.split('"')[1]
-                if "," in key_prefix:
-                  key_prefix = key_prefix.split(',')[0]
-              elif i > 0:
-                key = objectname.split('=')[2]
-                if key:
-                  if '"' in key:
-                    key = key.split('"')[1]
-                  key_prefix = key_prefix + '.' + key
+            # kafka.server:type=BrokerTopicMetrics,name=BytesRejectedPerSec,topic=escher_heartbeat_event
+            objectname = objectname.split(':')[1]
+            split_num = objectname.count(',')
+            if split_num == 0:
+              key_prefix = objectname.split('=')[1]
+            else:
+              for i in range(split_num + 1):
+                if i == 0:
+                  key_prefix = objectname.split(',')[i].split('=')[1]
+                elif i > 0:
+                  key = objectname.split(',')[i].split('=')[1]
+                  if key:
+                    key_prefix = key_prefix + '.' + key
 
         metrics = {}
`

**Comment by shortdudey123** [comment]
@ddreggors Looks like https://github.com/python-diamond/Diamond/pull/454 solves this as well... can you review and verify that is effectively the same as your patch?

**Comment by ddreggors** [comment]
It does, but that code also has some undesirable affects. See my comments in that ticket.

**Comment by shortdudey123** [comment]
yup, saw them :)

**Comment by shortdudey123** [comment]
@maauso this should be solved in master, open a new issue and reference this one if that is not the case

**Comment by ankitg1989** [comment]
I am able to get some of required data using mx4j tool in kafka 10 . But i am not getting metrics at topic level . say i need bytesfectched for all topics present in cluster

**Comment by zippycup** [comment]
Im running diamond (4.0.515)

KafkaCollector.conf
installed http://central.maven.org/maven2/mx4j/mx4j-tools/3.0.1/mx4j-tools-3.0.1.jar

netstat -plunt  | grep 8082
tcp        0      0 0.0.0.0:8082            0.0.0.0:*               LISTEN      1019/java

this is the url the collector constructs:
http://127.0.0.1:8082/mbean?operations=False&notifications=False&constructors=False&objectname=kafka.server%3Atype%3DFetcherLagMetrics%2Cname%3DConsumerLag%2CclientId%3DReplicaFetcherThread-0-2%2Ctopic%3D__consumer_offsets%2Cpartition%3D49&template=identity

I still get BadStatusLine error.

------------------------------

Try JolokiaCollector as well directly to the jmx port
jolokia_path= jmx

This get the same error:
1502985508.86   [JolokiaCollector:31104:ERROR]  /usr/lib/python2.7/site-packages/diamond/utils/scheduler.py:99
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/diamond/utils/scheduler.py", line 73, in collector_process
    collector._run()
  File "/usr/lib/python2.7/site-packages/diamond/collector.py", line 477, in _run
    self.collect()
  File "/usr/share/diamond/collectors/jolokia/jolokia.py", line 182, in collect
    self._get_domains()
  File "/usr/share/diamond/collectors/jolokia/jolokia.py", line 156, in _get_domains
    listing = self._list_request()
  File "/usr/share/diamond/collectors/jolokia/jolokia.py", line 225, in _list_request
    timeout=timeout)) as response:
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1244, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib64/python2.7/urllib2.py", line 1217, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib64/python2.7/httplib.py", line 1089, in getresponse
    response.begin()
  File "/usr/lib64/python2.7/httplib.py", line 444, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python2.7/httplib.py", line 408, in _read_status
    raise BadStatusLine(line)

**Comment by ankitg1989** [comment]
i am also able to get data using mx4j tool when download from http://mvnrepository.com/artifact/mx4j/mx4j-tools/3.0.1 but its not working when  i use mx4j which is present on https://sourceforge.net/projects/mx4j/files/MX4J%20Binary/ . Whats the different between them ?
