### ISSUE TITLE
Disk space collector doesn't work on devices with large st_dev

### ISSUE THREAD

**Issue by jaxxstorm** [python-diamond/Diamond#262]
os.major is casted as an int, so if your device has a magic number above the unsigned maximum, you get this lovely error:

```
Aug 31 00:41:49 web python: 1440978109.82   [DiskSpaceCollector:32617:ERROR]    Collector failed!
Aug 31 00:41:49 web python: 1440978109.82   [DiskSpaceCollector:32617:ERROR]    /usr/lib/python2.7/site-packages/diamond/utils/scheduler.py:99
Aug 31 00:41:49 web python: Traceback (most recent call last):
Aug 31 00:41:49 web python: File "/usr/lib/python2.7/site-packages/diamond/utils/scheduler.py", line 73, in collector_process
Aug 31 00:41:49 web python: collector._run()
Aug 31 00:41:49 web python: File "/usr/lib/python2.7/site-packages/diamond/collector.py", line 472, in _run
Aug 31 00:41:49 web python: self.collect()
Aug 31 00:41:49 web python: File "/usr/share/diamond/collectors/diskspace/diskspace.py", line 189, in collect
Aug 31 00:41:49 web python: results = self.get_file_systems()
Aug 31 00:41:49 web python: File "/usr/share/diamond/collectors/diskspace/diskspace.py", line 151, in get_file_systems
Aug 31 00:41:49 web python: major = os.major(stat.st_dev)
Aug 31 00:41:49 web python: OverflowError: signed integer is greater than maximum
```

The problem lies here:

```
# Working host, os.major is casted as an init
python -c "import os; stat = os.stat('/'); print type(os.major(stat.st_dev))"
<type 'int'>
# Not working host, value of st_dev is too high
python -c "import os; print os.stat('/');"
posix.stat_result(st_mode=16749, st_ino=2, st_dev=2592126593L, st_nlink=20, st_uid=0, st_gid=0, st_size=4096, st_atime=1440957760, st_mtime=1440957756, st_ctime=1440957756)
```

This is on python 2.7.5, default version on CentOS 7. It's patched in 2.7.9.

We can catch the error with OverflowError: but I think it might be best to rethink how we get the devices numbers..

**Comment by mzupan** [comment]
Can you paste your /proc/mounts so we can write a test case for this?

**Comment by jaxxstorm** [comment]
It's an OpenVZ/Virtuozzo guest

```
rootfs / rootfs rw 0 0
/dev/ploop39560p1 / ext4 rw,relatime,data=ordered,balloon_ino=12 0 0
none /sys sysfs rw,relatime,ve=1508301750 0 0
none /sys/fs/cgroup tmpfs rw,relatime,size=10149880k,nr_inodes=2537470 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpuacct,cpu 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/net_cls cgroup rw,nosuid,nodev,noexec,relatime,net_cls 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
proc /proc proc rw,relatime 0 0
devtmpfs /dev devtmpfs rw,nosuid,size=10149880k,nr_inodes=2537470,mode=755 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,nodev,mode=755 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/ve cgroup rw,nosuid,nodev,noexec,relatime,ve 0 0
cgroup /sys/fs/cgroup/beancounter cgroup rw,nosuid,nodev,noexec,relatime,beancounter 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
```

**Comment by mattrobenolt** [comment]
Does anybody know why we run these values through `os.{major,minor}` in the first place? I don't see anywhere these values get used, except to assert uniqueness in the devices.

`diskspace.py` literally does not use the values except for right here: https://github.com/python-diamond/Diamond/blob/master/src/collectors/diskspace/diskspace.py#L159-L166

And reason we can't just use the `stat.st_dev` value as they key instead? Not sure I understand why we're trying to coerce the major/minor values out, just to turn into a tuple. Seems like we can just compare the raw values.

**Comment by jaxxstorm** [comment]
This is essentially what I thought, and I patched it locally in this way. I figured there must be a reason I wasn't aware of.

I can submit a PR soonish which fixes this, if you're happy enough with it?

**Comment by mattrobenolt** [comment]
I can easily change that behavior, but no idea what the reason for that is.

This has existed since the beginning of time: https://github.com/python-diamond/Diamond/blob/f7c0bd3e23cea5be29e112259a5e0fcbd62fb655/src/collectors/diskspace/diskspace.py

Was looking for a commit that added it to see what the issue was that triggered needing it. :(

**Comment by mattrobenolt** [comment]
Ok, tracing all the way back through history, we get to: https://github.com/python-diamond/Diamond/commit/2b3c54a2e6c802dc18b083c12f6ac70a0783e0a6

Which is the initial commit. Since then, this behavior has existed. :) I'll do some investigation.
