### ISSUE TITLE
elasticsearch collector error when running with elasticsearch 2.1

### ISSUE THREAD

**Issue by jindov** [python-diamond/Diamond#343]
It occur when I start es collector with es 2.1:

```
[2015-12-11 14:44:01,691] [Thread-1] Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/diamond/collector.py", line 490, in _run
    self.collect()
  File "/usr/share/diamond/collectors/elasticsearch/elasticsearch.py", line 385, in collect
    self.collect_instance(alias, host, port)
  File "/usr/share/diamond/collectors/elasticsearch/elasticsearch.py", line 358, in collect_instance
    self._copy_two_level(metrics, 'network', data['network'])
KeyError: 'network'
```

I checked this collector with this "diamond-setup -C ElasticSearchCollector -p"
Collector not found.

eventhough I set enabled = True in conf

**Comment by MichaelDoyle** [comment]
@jindov I think if you pull down the latest, you'll be OK. The following commit should resolve your issue:

https://github.com/python-diamond/Diamond/commit/52f185ef43ad4047f66e803e8572759bf3e81f9e

**Comment by bmhatfield** [comment]
We're using recent diamond master in production with ES2.1, and as @MichaelDoyle says, things are working fine. Time to upgrade!
