### ISSUE TITLE
Unhandled exception: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by mrh666** [python-diamond/Diamond#385]
Hi there,

I can't start diamond on CentOS 7.0.1406
Python 2.7.5

```
# /usr/bin/python /usr/bin/diamond --log-stdout --foreground
1454020776.06   [MainProcess:1827:INFO] Changed UID: 0 () GID: 0 ().
1454020776.59   [MainProcess:1827:DEBUG]    Loading Handler diamond.handler.stats_d.StatsdHandler
1454020776.6    [MainProcess:1827:ERROR]    Unhandled exception: [Errno -2] Name or service not known
1454020776.6    [MainProcess:1827:ERROR]    /usr/bin/diamond:299
ERROR:diamond:Unhandled exception: [Errno -2] Name or service not known
1454020776.6    [MainProcess:1827:ERROR]    traceback: Traceback (most recent call last):
  File "/usr/bin/diamond", line 291, in main
    server.run()
  File "/usr/lib/python2.7/site-packages/diamond/server.py", line 104, in run
    self.handlers = load_handlers(self.config, handlers)
  File "/usr/lib/python2.7/site-packages/diamond/utils/classes.py", line 87, in load_handlers
    h = cls(handler_config)
  File "/usr/lib/python2.7/site-packages/diamond/handler/stats_d.py", line 61, in __init__
    self._connect()
  File "/usr/lib/python2.7/site-packages/diamond/handler/stats_d.py", line 154, in _connect
    port=self.port
  File "/usr/lib/python2.7/site-packages/statsd/client.py", line 139, in __init__
    host, port, fam, socket.SOCK_DGRAM)[0]
gaierror: [Errno -2] Name or service not known

1454020776.6    [MainProcess:1827:ERROR]    /usr/bin/diamond:300
ERROR:diamond:traceback: Traceback (most recent call last):
  File "/usr/bin/diamond", line 291, in main
    server.run()
  File "/usr/lib/python2.7/site-packages/diamond/server.py", line 104, in run
    self.handlers = load_handlers(self.config, handlers)
  File "/usr/lib/python2.7/site-packages/diamond/utils/classes.py", line 87, in load_handlers
    h = cls(handler_config)
  File "/usr/lib/python2.7/site-packages/diamond/handler/stats_d.py", line 61, in __init__
    self._connect()
  File "/usr/lib/python2.7/site-packages/diamond/handler/stats_d.py", line 154, in _connect
    port=self.port
  File "/usr/lib/python2.7/site-packages/statsd/client.py", line 139, in __init__
    host, port, fam, socket.SOCK_DGRAM)[0]
gaierror: [Errno -2] Name or service not known
```

```
# pip list
backports.ssl-match-hostname (3.4.0.2)
boto (2.25.0)
cffi (1.5.0)
chardet (2.0.1)
Cheetah (2.4.4)
cloud-init (0.7.5)
configobj (4.7.2)
cryptography (1.2.1)
decorator (3.4.0)
diamond (4.0.128)
enum34 (1.1.2)
idna (2.0)
iniparse (0.4)
ipaddress (1.0.16)
IPy (0.75)
javapackages (1.0.0)
jsonpatch (1.2)
jsonpointer (1.0)
kitchen (1.1.1)
lxml (3.2.1)
Markdown (2.4.1)
ndg-httpsclient (0.4.0)
Pillow (2.0.0)
pip (7.1.0)
policycoreutils-default-encoding (0.1)
portstat (0.0.6)
prettytable (0.7.2)
psutil (3.4.2)
pyasn1 (0.1.9)
pycparser (2.14)
pycurl (7.19.0)
Pygments (1.4)
pygobject (3.8.2)
pygpgme (0.3)
pyliblzma (0.5.3)
pyOpenSSL (0.15.1)
pyudev (0.15)
pyxattr (0.5.1)
PyYAML (3.10)
requests (1.1.0)
seobject (0.1)
sepolicy (1.1)
setuptools (19.6.1)
six (1.10.0)
statsd (3.2.1)
urlgrabber (3.10)
urllib3 (1.5)
yum-metadata-parser (1.1.4)
```

```
[server]
handlers = diamond.handler.stats_d.StatsdHandler
user =
group =
pid_file = /var/run/diamond.pid
collectors_path = /usr/share/diamond/collectors/
collectors_config_path = /etc/diamond/collectors/
handlers_config_path = /etc/diamond/handlers/
collectors_reload_interval = 3600

[handlers]
keys = rotated_file

[[default]]

[[ArchiveHandler]]
log_file = /var/log/diamond/archive.log
days = 7

[[GraphiteHandler]]
host = false
port = 2003
proto = TCP
timeout = 15
batch = 1

[[GraphitePickleHandler]]
host = false
port = 2004
timeout = 15
batch = 256

[[MySQLHandler]]

hostname    = 127.0.0.1
port        = 3306
username    = root
password    =
database    = diamond
table       = metrics
col_time    = timestamp
col_metric  = metric
col_value   = value

[[StatsdHandler]]
host = graphiterelay.myrealdomain.com
port = 8125

[[TSDBHandler]]
host = 127.0.0.1
port = 4242
timeout = 15

[[LibratoHandler]]
user = false
apikey = false

[[RiemannHandler]]
host = false
port = 5555
transport = tcp

[collectors]

[[default]]
hostname = myrealhostname-ipaddr
path_prefix = servers.dev.myrealhostname
interval = 60

[loggers]
keys = root

[formatters]
keys = default

[logger_root]
level = WARNING
handlers = rotated_file
propagate = 1

[handler_rotated_file]
class = handlers.TimedRotatingFileHandler
level = WARNING
formatter = default
args = ('/var/log/diamond/diamond.log', 'midnight', 1, 7)

[formatter_default]
format = [%(asctime)s] [%(threadName)s] %(message)s
datefmt =
```

Any idea how can I fix it please?

**Comment by redref** [comment]
Your host "graphiterelay.myrealdomain.com" cannot be resolved ("Name or service not known" really look like it's DNS related). You may solve your problem by providing valid statsd connection host.

Nevertheless, Stats_d handler does not catch connection errors (graphite handler do by example). This may require correction (or not).

**Comment by quiqueporta** [comment]
I have the same issue

**Comment by josegonzalez** [comment]
You've set the host to `false` for a few collectors. You may instead wish to disable them (or omit them from your config).
