### ISSUE TITLE
Solr Collector breaks using solr 5.4.0 cloud.

### ISSUE THREAD

**Issue by JasonJanelle** [python-diamond/Diamond#388]
Not sure if this has been tested with solr cloud / solr 5.4.0 but I'm getting this in my diamond.log and no stats.

[2016-02-06 05:52:38,532] [MainThread] Collector failed!
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/diamond/utils/scheduler.py", line 70, in collector_process
    collector._run()
  File "/usr/lib/python2.7/dist-packages/diamond/collector.py", line 472, in _run
    self.collect()
  File "/usr/share/diamond/collectors/solr/solr.py", line 147, in collect
    standard = stats["QUERYHANDLER"]["standard"]["stats"]
KeyError: 'standard'

**Comment by JasonJanelle** [comment]
I'm happy to provide more detail on our setup if that is needed.

**Comment by brijesh27** [comment]
Hi Jason ,

I was having the same problem , its fix by below thing so Please try this : 

https://github.com/piontas/Diamond/commit/f5c8ddd589627a9ef21014c6161f9f3fb6c94bcb
