### ISSUE TITLE
HTTPJSONCollector

### ISSUE THREAD

**Issue by akmalabbasov** [python-diamond/Diamond#479]
Hi, I have a following json file returned by http request.

```
{
    "counters": {},
    "gauges": {
        "jvm.PS-MarkSweep.count": {
            "value": 1
        },
       ...
    }
}
```

I'm using HTTPJSONCollector, but getting the following errror

```
2016-05-31 15:08:29,603 [MainThread] name: gauges
2016-05-31 15:08:29,606 [MainThread] Collector failed!
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/diamond/utils/scheduler.py", line 73, in collector_process
    collector._run()
  File "/usr/lib/pymodules/python2.7/diamond/collector.py", line 473, in _run
    self.collect()
  File "/usr/share/diamond/collectors/httpjson/httpjson.py", line 100, in collect
    self._collect()
  File "/usr/share/diamond/collectors/httpjson/httpjson.py", line 90, in _collect
    self.publish(stat_name, metric_value)
  File "/usr/lib/pymodules/python2.7/diamond/collector.py", line 393, in publish
    metric_type=metric_type, ttl=ttl)
  File "/usr/lib/pymodules/python2.7/diamond/metric.py", line 57, in __init__
    value = round(float(value))
TypeError: float() argument must be a string or a number
```

**Comment by redref** [comment]
Can you please provide collector config and version ?

Right now, it's impossible to match any lines. I could not find :
`self.publish(stat_name, metric_value)`

**Comment by josegonzalez** [comment]
Closing as there hasn't been any followup. Feel free to comment with your configuration and diamond version so we can further investigate.
