### ISSUE TITLE
tox -e py27 test failing

### ISSUE THREAD

**Issue by ajkumarnv** [python-diamond/Diamond#669]
FAIL: test_batch (testtsdb.TestTSDBdHandler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/murphy/Diamond-master/src/diamond/handler/test/testtsdb.py", line 115, in test_batch
    mock_urlopen.assert_called_with(self.url, body, header)
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/mock/mock.py", line 937, in assert_called_with
    six.raise_from(AssertionError(_error_message(cause)), cause)
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/six.py", line 718, in raise_from
    raise value
AssertionError: Expected call: Request('http://127.0.0.1:4242/api/put', '[{"timestamp": 1234567, "metric": "cpu.cpu_count", "value": 123, "tags": {"hostname": "myhostname"}}, {"timestamp": 5678910, "metric": "cpu.cpu_time", "value": 123, "tags": {"hostname": "myhostname"}}]', {'Content-Type': 'application/json'})
Actual call: Request('http://127.0.0.1:4242/api/put', '[{"value": 123, "tags": {"hostname": "myhostname"}, "metric": "cpu.cpu_count", "timestamp": 1234567}, {"value": 123, "tags": {"hostname": "myhostname"}, "metric": "cpu.cpu_time", "timestamp": 5678910}]', {'Content-Type': 'application/json'})

======================================================================
FAIL: test_compression (testtsdb.TestTSDBdHandler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/murphy/Diamond-master/src/diamond/handler/test/testtsdb.py", line 76, in test_compression
    assert self.decompress(passed_body) == body
AssertionError

======================================================================
FAIL: test_cpu_metrics_taghandling_0 (testtsdb.TestTSDBdHandler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/murphy/Diamond-master/src/diamond/handler/test/testtsdb.py", line 187, in test_cpu_metrics_taghandling_0
    mock_urlopen.assert_called_with(self.url, body, header)
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/mock/mock.py", line 937, in assert_called_with
    six.raise_from(AssertionError(_error_message(cause)), cause)
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/six.py", line 718, in raise_from
    raise value
AssertionError: Expected call: Request('http://127.0.0.1:4242/api/put', '[{"timestamp": 1234567, "metric": "cpu.cpu0.user", "value": 123, "tags": {"myFirstTag": "myValue", "hostname": "myhostname"}}]', {'Content-Type': 'application/json'})
Actual call: Request('http://127.0.0.1:4242/api/put', '[{"value": 123, "tags": {"myFirstTag": "myValue", "hostname": "myhostname"}, "metric": "cpu.cpu0.user", "timestamp": 1234567}]', {'Content-Type': 'application/json'})

======================================================================
FAIL: test_cpu_metrics_taghandling_1 (testtsdb.TestTSDBdHandler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/murphy/Diamond-master/src/diamond/handler/test/testtsdb.py", line 226, in test_cpu_metrics_taghandling_1
    mock_urlopen.assert_called_with(self.url, body, header)
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/mock/mock.py", line 937, in assert_called_with
    six.raise_from(AssertionError(_error_message(cause)), cause)
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/six.py", line 718, in raise_from
    raise value
AssertionError: Expected call: Request('http://127.0.0.1:4242/api/put', '[{"timestamp": 1234567, "metric": "cpu.total.user", "value": 123, "tags": {"myFirstTag": "myValue", "hostname": "myhostname"}}]', {'Content-Type': 'application/json'})
Actual call: Request('http://127.0.0.1:4242/api/put', '[{"value": 123, "tags": {"myFirstTag": "myValue", "hostname": "myhostname"}, "metric": "cpu.total.user", "timestamp": 1234567}]', {'Content-Type': 'application/json'})

======================================================================
FAIL: test_cpu_metrics_taghandling_2 (testtsdb.TestTSDBdHandler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/murphy/Diamond-master/src/diamond/handler/test/testtsdb.py", line 249, in test_cpu_metrics_taghandling_2
    mock_urlopen.assert_called_with(self.url, body, header)
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/mock/mock.py", line 937, in assert_called_with
    six.raise_from(AssertionError(_error_message(cause)), cause)
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/six.py", line 718, in raise_from
    raise value
AssertionError: Expected call: Request('http://127.0.0.1:4242/api/put', '[{"timestamp": 1234567, "metric": "cpu.user", "value": 123, "tags": {"cpuId": "total", "myFirstTag": "myValue", "hostname": "myhostname"}}]', {'Content-Type': 'application/json'})
Actual call: Request('http://127.0.0.1:4242/api/put', '[{"value": 123, "tags": {"myFirstTag": "myValue", "hostname": "myhostname", "cpuId": "total"}, "metric": "cpu.user", "timestamp": 1234567}]', {'Content-Type': 'application/json'})

======================================================================
FAIL: test_diskspace_metrics (testtsdb.TestTSDBdHandler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/murphy/Diamond-master/src/diamond/handler/test/testtsdb.py", line 341, in test_diskspace_metrics
    mock_urlopen.assert_called_with(self.url, body, header)
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/mock/mock.py", line 937, in assert_called_with
    six.raise_from(AssertionError(_error_message(cause)), cause)
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/six.py", line 718, in raise_from
    raise value
AssertionError: Expected call: Request('http://127.0.0.1:4242/api/put', '[{"timestamp": 1234567, "metric": "diskspace.MOUNT_POINT.byte_percentfree", "value": 80, "tags": {"myFirstTag": "myValue", "hostname": "myhostname"}}]', {'Content-Type': 'application/json'})
Actual call: Request('http://127.0.0.1:4242/api/put', '[{"value": 80, "tags": {"myFirstTag": "myValue", "hostname": "myhostname"}, "metric": "diskspace.MOUNT_POINT.byte_percentfree", "timestamp": 1234567}]', {'Content-Type': 'application/json'})

======================================================================
FAIL: test_diskspace_metrics_default (testtsdb.TestTSDBdHandler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/murphy/Diamond-master/src/diamond/handler/test/testtsdb.py", line 318, in test_diskspace_metrics_default
    mock_urlopen.assert_called_with(self.url, body, header)
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/mock/mock.py", line 937, in assert_called_with
    six.raise_from(AssertionError(_error_message(cause)), cause)
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/six.py", line 718, in raise_from
    raise value
AssertionError: Expected call: Request('http://127.0.0.1:4242/api/put', '[{"timestamp": 1234567, "metric": "diskspace.byte_percentfree", "value": 80, "tags": {"mountpoint": "MOUNT_POINT", "myFirstTag": "myValue", "hostname": "myhostname"}}]', {'Content-Type': 'application/json'})
Actual call: Request('http://127.0.0.1:4242/api/put', '[{"value": 80, "tags": {"myFirstTag": "myValue", "hostname": "myhostname", "mountpoint": "MOUNT_POINT"}, "metric": "diskspace.byte_percentfree", "timestamp": 1234567}]', {'Content-Type': 'application/json'})

======================================================================
FAIL: test_haproxy_metrics (testtsdb.TestTSDBdHandler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/murphy/Diamond-master/src/diamond/handler/test/testtsdb.py", line 295, in test_haproxy_metrics
    mock_urlopen.assert_called_with(self.url, body, header)
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/mock/mock.py", line 937, in assert_called_with
    six.raise_from(AssertionError(_error_message(cause)), cause)
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/six.py", line 718, in raise_from
    raise value
AssertionError: Expected call: Request('http://127.0.0.1:4242/api/put', '[{"timestamp": 1234567, "metric": "haproxy.SOME-BACKEND.SOME-SERVER.bin", "value": 123, "tags": {"myFirstTag": "myValue", "hostname": "myhostname"}}]', {'Content-Type': 'application/json'})
Actual call: Request('http://127.0.0.1:4242/api/put', '[{"value": 123, "tags": {"myFirstTag": "myValue", "hostname": "myhostname"}, "metric": "haproxy.SOME-BACKEND.SOME-SERVER.bin", "timestamp": 1234567}]', {'Content-Type': 'application/json'})

======================================================================
FAIL: test_haproxy_metrics_default (testtsdb.TestTSDBdHandler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/murphy/Diamond-master/src/diamond/handler/test/testtsdb.py", line 272, in test_haproxy_metrics_default
    mock_urlopen.assert_called_with(self.url, body, header)
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/mock/mock.py", line 937, in assert_called_with
    six.raise_from(AssertionError(_error_message(cause)), cause)
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/six.py", line 718, in raise_from
    raise value
AssertionError: Expected call: Request('http://127.0.0.1:4242/api/put', '[{"timestamp": 1234567, "metric": "haproxy.bin", "value": 123, "tags": {"backend": "SOME-BACKEND", "myFirstTag": "myValue", "hostname": "myhostname", "server": "SOME-SERVER"}}]', {'Content-Type': 'application/json'})
Actual call: Request('http://127.0.0.1:4242/api/put', '[{"value": 123, "tags": {"backend": "SOME-BACKEND", "myFirstTag": "myValue", "hostname": "myhostname", "server": "SOME-SERVER"}, "metric": "haproxy.bin", "timestamp": 1234567}]', {'Content-Type': 'application/json'})

======================================================================
FAIL: test_iostat_metrics (testtsdb.TestTSDBdHandler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/murphy/Diamond-master/src/diamond/handler/test/testtsdb.py", line 384, in test_iostat_metrics
    mock_urlopen.assert_called_with(self.url, body, header)
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/mock/mock.py", line 937, in assert_called_with
    six.raise_from(AssertionError(_error_message(cause)), cause)
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/six.py", line 718, in raise_from
    raise value
AssertionError: Expected call: Request('http://127.0.0.1:4242/api/put', '[{"timestamp": 1234567, "metric": "iostat.DEV.io_in_progress", "value": 80, "tags": {"myFirstTag": "myValue", "hostname": "myhostname"}}]', {'Content-Type': 'application/json'})
Actual call: Request('http://127.0.0.1:4242/api/put', '[{"value": 80, "tags": {"myFirstTag": "myValue", "hostname": "myhostname"}, "metric": "iostat.DEV.io_in_progress", "timestamp": 1234567}]', {'Content-Type': 'application/json'})

======================================================================
FAIL: test_iostat_metrics_default (testtsdb.TestTSDBdHandler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/murphy/Diamond-master/src/diamond/handler/test/testtsdb.py", line 362, in test_iostat_metrics_default
    mock_urlopen.assert_called_with(self.url, body, header)
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/mock/mock.py", line 937, in assert_called_with
    six.raise_from(AssertionError(_error_message(cause)), cause)
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/six.py", line 718, in raise_from
    raise value
AssertionError: Expected call: Request('http://127.0.0.1:4242/api/put', '[{"timestamp": 1234567, "metric": "iostat.io_in_progress", "value": 80, "tags": {"device": "DEV", "myFirstTag": "myValue", "hostname": "myhostname"}}]', {'Content-Type': 'application/json'})
Actual call: Request('http://127.0.0.1:4242/api/put', '[{"value": 80, "tags": {"myFirstTag": "myValue", "hostname": "myhostname", "device": "DEV"}, "metric": "iostat.io_in_progress", "timestamp": 1234567}]', {'Content-Type': 'application/json'})

======================================================================
FAIL: test_network_metrics (testtsdb.TestTSDBdHandler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/murphy/Diamond-master/src/diamond/handler/test/testtsdb.py", line 427, in test_network_metrics
    mock_urlopen.assert_called_with(self.url, body, header)
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/mock/mock.py", line 937, in assert_called_with
    six.raise_from(AssertionError(_error_message(cause)), cause)
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/six.py", line 718, in raise_from
    raise value
AssertionError: Expected call: Request('http://127.0.0.1:4242/api/put', '[{"timestamp": 1234567, "metric": "network.IF.rx_packets", "value": 80, "tags": {"myFirstTag": "myValue", "hostname": "myhostname"}}]', {'Content-Type': 'application/json'})
Actual call: Request('http://127.0.0.1:4242/api/put', '[{"value": 80, "tags": {"myFirstTag": "myValue", "hostname": "myhostname"}, "metric": "network.IF.rx_packets", "timestamp": 1234567}]', {'Content-Type': 'application/json'})

======================================================================
FAIL: test_network_metrics_default (testtsdb.TestTSDBdHandler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/murphy/Diamond-master/src/diamond/handler/test/testtsdb.py", line 405, in test_network_metrics_default
    mock_urlopen.assert_called_with(self.url, body, header)
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/mock/mock.py", line 937, in assert_called_with
    six.raise_from(AssertionError(_error_message(cause)), cause)
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/six.py", line 718, in raise_from
    raise value
AssertionError: Expected call: Request('http://127.0.0.1:4242/api/put', '[{"timestamp": 1234567, "metric": "network.rx_packets", "value": 80, "tags": {"interface": "IF", "myFirstTag": "myValue", "hostname": "myhostname"}}]', {'Content-Type': 'application/json'})
Actual call: Request('http://127.0.0.1:4242/api/put', '[{"value": 80, "tags": {"myFirstTag": "myValue", "hostname": "myhostname", "interface": "IF"}, "metric": "network.rx_packets", "timestamp": 1234567}]', {'Content-Type': 'application/json'})

======================================================================
FAIL: test_prefix (testtsdb.TestTSDBdHandler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/murphy/Diamond-master/src/diamond/handler/test/testtsdb.py", line 147, in test_prefix
    mock_urlopen.assert_called_with(self.url, body, header)
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/mock/mock.py", line 937, in assert_called_with
    six.raise_from(AssertionError(_error_message(cause)), cause)
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/six.py", line 718, in raise_from
    raise value
AssertionError: Expected call: Request('http://127.0.0.1:4242/api/put', '[{"timestamp": 1234567, "metric": "diamond.cpu.cpu_count", "value": 123, "tags": {"hostname": "myhostname"}}]', {'Content-Type': 'application/json'})
Actual call: Request('http://127.0.0.1:4242/api/put', '[{"value": 123, "tags": {"hostname": "myhostname"}, "metric": "diamond.cpu.cpu_count", "timestamp": 1234567}]', {'Content-Type': 'application/json'})

======================================================================
FAIL: test_single_metric (testtsdb.TestTSDBdHandler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/murphy/Diamond-master/src/diamond/handler/test/testtsdb.py", line 58, in test_single_metric
    mock_urlopen.assert_called_with(self.url, body, header)
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/mock/mock.py", line 937, in assert_called_with
    six.raise_from(AssertionError(_error_message(cause)), cause)
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/six.py", line 718, in raise_from
    raise value
AssertionError: Expected call: Request('http://127.0.0.1:4242/api/put', '[{"timestamp": 1234567, "metric": "cpu.cpu_count", "value": 123, "tags": {"hostname": "myhostname"}}]', {'Content-Type': 'application/json'})
Actual call: Request('http://127.0.0.1:4242/api/put', '[{"value": 123, "tags": {"hostname": "myhostname"}, "metric": "cpu.cpu_count", "timestamp": 1234567}]', {'Content-Type': 'application/json'})

======================================================================
FAIL: test_tags (testtsdb.TestTSDBdHandler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/murphy/Diamond-master/src/diamond/handler/test/testtsdb.py", line 132, in test_tags
    mock_urlopen.assert_called_with(self.url, body, header)
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/mock/mock.py", line 937, in assert_called_with
    six.raise_from(AssertionError(_error_message(cause)), cause)
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/six.py", line 718, in raise_from
    raise value
AssertionError: Expected call: Request('http://127.0.0.1:4242/api/put', '[{"timestamp": 1234567, "metric": "cpu.cpu_count", "value": 123, "tags": {"hostname": "myhostname", "tag1": "tagv1", "tag2": "tagv2"}}]', {'Content-Type': 'application/json'})
Actual call: Request('http://127.0.0.1:4242/api/put', '[{"value": 123, "tags": {"tag2": "tagv2", "tag1": "tagv1", "hostname": "myhostname"}, "metric": "cpu.cpu_count", "timestamp": 1234567}]', {'Content-Type': 'application/json'})

======================================================================
FAIL: test_user_password (testtsdb.TestTSDBdHandler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/murphy/Diamond-master/src/diamond/handler/test/testtsdb.py", line 91, in test_user_password
    mock_urlopen.assert_called_with(self.url, body, header)
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/mock/mock.py", line 937, in assert_called_with
    six.raise_from(AssertionError(_error_message(cause)), cause)
  File "/home/murphy/Diamond-master/.tox/py27/local/lib/python2.7/site-packages/six.py", line 718, in raise_from
    raise value
AssertionError: Expected call: Request('http://127.0.0.1:4242/api/put', '[{"timestamp": 1234567, "value": 123, "metric": "cpu.cpu_count", "tags": {"hostname": "myhostname"}}]', {'Authorization': 'Basic Sm9obiBEb2U6MTIzNDU2Nzg5', 'Content-Type': 'application/json'})
Actual call: Request('http://127.0.0.1:4242/api/put', '[{"value": 123, "tags": {"hostname": "myhostname"}, "metric": "cpu.cpu_count", "timestamp": 1234567}]', {'Authorization': 'Basic Sm9obiBEb2U6MTIzNDU2Nzg5', 'Content-Type': 'application/json'})

----------------------------------------------------------------------
Ran 558 tests in 6.263s

FAILED (failures=17)
ERROR: InvocationError: '/home/murphy/Diamond-master/test.py'

**Comment by shortdudey123** [comment]
See PR#671 for the solution.
