### ISSUE TITLE
Failure in mysql collector for diamond-4.0

### ISSUE THREAD

**Issue by williamjoy** [python-diamond/Diamond#672]
```python
==> /var/log/diamond/diamond.log <==
[2017-08-10 02:54:59,651] [MainThread] Collector failed!
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/diamond/utils/scheduler.py", line 77, in collector_process
    collector._run()
  File "/usr/lib/python2.7/site-packages/diamond/collector.py", line 477, in _run
    self.collect()
  File "/usr/share/diamond/collectors/mysqlstat/mysqlstat.py", line 477, in collect
    self.disconnect()
  File "/usr/share/diamond/collectors/mysqlstat/mysqlstat.py", line 313, in disconnect
    self.db.close()
AttributeError: 'NoneType' object has no attribute 'close'
```

**Comment by williamjoy** [comment]
for temp skip the error,

```diff
     def disconnect(self):
-        self.db.close()
+        if hasattr(self, 'db'):
+            self.db.close()
 
```

**Comment by shortdudey123** [comment]
Based on the limited info, I am guessing there is an uncaught exception in the connect method when trying to define self.db.  You could add some debug lines to narrow it down.
